### PR TITLE
Reorganize repository 2nd attempt

### PR DESCRIPTION
**Pull request by stephanboersma**
Hi guys,

After our discussion Monday, I thought that I might be able to help out a little bit with cleaning up/simplifying the repository.

Then it should be easier for you to continue development. I did test locally but it is probably a good idea if one of you also run some tests :-)

You are of course free to accept or decline these updates.

**Updates 23rd of February**
1. Renamed CLI command from `react-bratus` to `bratus`. Personally, I think this gives a better experience in the terminal. Can easily be undone
2. _Parser_ classes and the `Server` class are now part of the `packages/cli` and are compiled together
3. Updated the `yarn run build`script. It will now compile the CLI and the React app, then move build files to the cli/bin, ~and finally link the cli locally for testing.~ 
4. Remove `.DS_Store` and `lerna-debug.log` files + added them to `.gitignore`.
5. `/bin`and `/build` folders are also added to `.gitignore`. Note: Publishing a new version to npmjs would require the `bin` folder. Branching out to include the `bin`folder is required in the process.
6. Updated `README.md` to include a section about the development environment + reflect the command change from `react-bratus` to `bratus`

**Updates 2nd of March**
1. Update import statement in Server.ts
2. Update tsconfig.eslint.json to target the correct folders after renaming
3. Update build script to remove old builds before making new builds. 
4. Removed `yarn run link-cli` from the build script. This must be run separately
5. Replaced `yarn link` with `npm link` in the `link-cli` command. [Due this issue](https://github.com/yarnpkg/yarn/issues/3587)

### CODE REVIEW

**Review by thepiotrek — COMMENTED** [review]
Nice job! 

I tested this:
- cloned a fresh copy from GH
- `yarn install`
- `yarn run build`
- `yarn run link-cli` (I just needed to delete the old link file from `/usr/local/bin`)

Realy like the organization now and new .gitignore structure.

**Review by thepiotrek — APPROVED** [review]

**Comment by Evgenios95** [comment]
Looks nice and clean 😄 
@thepiotrek let's merge it when you come here today. Might need your Mac knowledge to delete files from bin and stuff xD

**Comment by Evgenios95** [comment]
Since this refactoring happened, I get a zsh: permission denied every time I run bratus on a project.
I fix the issue with Piotrek's help but then I get the same error the next day. Is there a way to fix this? I tried to find a way of doing that, but didn't really find a solution

**Comment by Evgenios95** [comment]
@stephanboersma

**Comment by stephanboersma** [comment]
@Evgenios95,

It is required to make the `packages/bratus-cli/bin/index.js` executable by running `chmod u+x packages/bratus-cli/bin/index.js` to run the command.

According to documentation, the `npm link` command should take care of the permissions but a lot are experiencing trouble with this.

The recurring need to make the bin/index.js executable is because of the remove-builds script that is removing all build files each time you make a new build. This command was introduced to avoid complications with moving the app build files to the bin folder. Therefore, the solution is to update the remove-builds script from:
`"remove-builds": "rm -rf ./packages/bratus-cli/bin && rm -rf ./packages/bratus-app/build"`
to
`"remove-builds": "rm -rf ./packages/bratus-cli/bin/bratus-app && rm -rf ./packages/bratus-app/build"`

This way, the bin/index.js file is not deleted upon every build. Let me know if it works out :-)

**Pull request merged**
